version: "3.8"

services:
  agendador-tarefas:
    build: ..\agendador-tarefas\agendador-tarefas
    container_name: agendador-tarefas
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/db_agendador
    depends_on:
      - mongo
  bff-agendador-tarefas:
    build: .
    container_name: bff-agendador-tarefas
    ports:
      - "8083:8083"
    environment:
      - USUARIO_URL=usuario:8080/usuario
      - AGENDADOR_TAREFAS_URL=agendador-tarefas:8081/tarefas
      - NOTIFICACAO_URL=notificacao:8082/email
  usuario:
    build: ..\usuario
    container_name: usuario
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_usuario
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
  notificacao:
    build: ..\notificacao
    container_name: notificacao
    ports:
      - "8082:8082"
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_usuario
    ports:
      - "5433:5432"
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: no
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_agendador
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
  mongo-config: